export declare const PROVIDER_ID = "modal";
export declare const DEFAULT_GATEWAY_BASE_URL = "http://92.5.60.87:4100/modal/v1";
export declare const DEFAULT_POOL_ADMIN_BASE_URL = "http://92.5.60.87:4100/modal";
export declare const DEFAULT_MODAL_BASE_URL = "https://api.us-west-2.modal.direct/v1";
export declare const DEFAULT_POOL_TIMEOUT_MS = 8000;
export declare const DEFAULT_WAIT_TIMEOUT_SECONDS = 5;
export declare const DEFAULT_COOLDOWN_SECONDS = 60;
export declare const DEFAULT_MAX_RETRIES = 2;
//# sourceMappingURL=constants.d.ts.map